name: C++ CI/CD with itch.io deployment

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install dependencies
      run: sudo apt-get install -y g++ cmake

    - name: Build
      run: |
        mkdir build
        cd build
        cmake ..
        make

  deploy:
    needs: build-and-test
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install butler
      run: |
        curl -L -o butler.zip https://broth.itch.ovh/butler/linux-amd64/LATEST/archive/default
        unzip butler.zip
        chmod +x butler
        sudo mv butler /usr/bin/

    - name: Authenticate with itch.io
      run: butler login --api-key ${{ VEN5lz4dHVe8Y0EwtCwcErpGLLRNfuv2GmhyOEN1 }}

    - name: Push to itch.io
      run: butler push ./build idSynth/cicd-test-game:windows-beta
