name: C++ CI/CD with itch.io deployment

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1

    - name: Build solution
      run: msbuild ./Game_Finished/GameTest.sln /p:Configuration=Release /p:OutDir=./BuildResult/Game/

  deploy:
    needs: build-and-test
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install butler
      shell: powershell
      run: |
        Invoke-WebRequest -Uri https://broth.itch.ovh/butler/windows-amd64/LATEST/archive/default -OutFile butler.zip
        Expand-Archive butler.zip -DestinationPath ./
        mv .\butler.exe C:\Windows

    - name: Push to itch.io
      env:
         BUTLER_API_KEY: ${{ secrets.BUTLER_API_KEY }}
      run: butler push ./BuildResult/Game/ idSynth/cicd-test-game:windows-beta
